# Site Settings
title:               IAmSzili
tagline:             casual thinker
description:         
baseurl:             #""
url:                 #"http://localhost:4000"
github:
  url:               "https://nemesszili.github.io"
author:
  name:              "Szilárd Nemes"
  email:             "nemesszili@gmail.com"
  github:            "nemesszili"
  linkedin:          "nemesszili"
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
